### ISSUE TITLE
Bug in commonmark 0.13

### ISSUE THREAD

**Issue by beaubbe** [jensscherbl/commonmark#1]
Can the commonmark be updated to latest version. There seems to be some bugs in the 0.13 version. I can't have a string starting or ending with "0" in bold (the double "*" will be outputed instaed of having a strong tag). The problem seems to be resolved on commonmark 0.16.

**Comment by jensscherbl** [comment]
Sure, will push an update tomorrow.

**Comment by beaubbe** [comment]
Thanks

**Comment by jensscherbl** [comment]
Created a [new branch][1] with support for the latest [CommonMark Spec 0.17][2].

Can you please give it a try and let me know if everything works as expected?

[1]: https://github.com/jensscherbl/commonmark/tree/0.1.4
[2]: http://spec.commonmark.org/0.17/

**Comment by beaubbe** [comment]
Thanks. I'll try it tomorrow

**Comment by beaubbe** [comment]
The problem is not solved. I tought updating commonmark would fix it. The problem is not there in the online editor of commonmark (http://spec.commonmark.org/dingus/). I'll try looking into it.

**Comment by jensscherbl** [comment]
Maybe it's a bug in the [CommonMark library][1] I use. Maybe you should [report your issue there][2].

[1]: https://github.com/thephpleague/commonmark
[2]: https://github.com/thephpleague/commonmark/issues
