### ISSUE TITLE
Markdown not being formatted

### ISSUE THREAD

**Issue by DavidOliver** [jensscherbl/commonmark#2]
Hi @jensscherbl,

I may well be doing something stupid, but I'm finding that the `formatted` mode doesn't contain HTML elements.

I'm using Symphony 2.6.0 and only have two extensions installed: Debug Devkit and CommonMark. CommonMark 0.1.4 is enabled.

Screenshot below showing the section, data source, extensions directory and XML debug page.

Any ideas? Thanks.

![screenshot from 2015-03-26 14 55 34](https://cloud.githubusercontent.com/assets/192853/6847719/e556140a-d3c8-11e4-8ff1-208707c2cc41.png)

**Comment by jensscherbl** [comment]
Will look into it later today.

**Comment by jensscherbl** [comment]
Sorry, can't reproduce your issue.

> I'm using Symphony 2.6.0

Did you try with `2.6.1`?

**Comment by DavidOliver** [comment]
I have updated to 2.6.1 now, yes. However, I think it must have been to do with the order in which I set things up as re-saving the entry sorted it.

Sorry to waste your time. :/ Thanks for the extension.

**Comment by jensscherbl** [comment]
> I think it must have been to do with the order in which I set things up as re-saving the entry, which I've just done, sorted it.

If you create the entry first and add the formatter later, the entry needs to be re-saved since formatters currently run and store their output on entry creation. But I'm [already working on that][1] as well... ;)

[1]: https://github.com/jensscherbl/textareanew#implementation-details

**Comment by DavidOliver** [comment]
Heh - nice. Thanks again.
