### ISSUE TITLE
Formatter issue with the dashboard extensions

### ISSUE THREAD

**Issue by nitriques** [jensscherbl/commonmark#3]
The dashboard loads the Formatter Class without require'ing the autoloader.

A simple

```php
require_once(EXTENSIONS . '/commonmark/vendor/autoload.php');
```

Inserted at line 3 does the job. Would you mind adding it please ?

Thanks.

**Comment by jensscherbl** [comment]
You mean [like this][1]? oO

[1]: https://github.com/jensscherbl/commonmark/blob/master/text-formatters/formatter.commonmark.php#L3

**Comment by nitriques** [comment]
Yup! Thanks!
